/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.42
 * Generated at: 2025-06-17 05:25:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.el;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class _01_005f1_005fel_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<form action=\"");
      out.print( request.getContextPath() );
      out.write("/myEl.do\" method=\"post\"> \r\n");
      out.write("	<!-- action을 myEl.do 로만 해놓으면 http://localhost:8080/whiteTiger/el/myEl.do 이렇게 들어가짐, -->\r\n");
      out.write("	<!-- 위에서 처럼 함녀 http://localhost:8080/whiteTiger/myEl.do 이케됨(전송 눌렀을때) -->\r\n");
      out.write("		<h2>개인정보 입력</h2>\r\n");
      out.write("		이름 : <input type=\"text\" name=\"name\" id=\"name\"><br/>\r\n");
      out.write("		성별 : <input type=\"radio\" name=\"gender\" value=\"남\"/>남자\r\n");
      out.write("			 <input type=\"radio\" name=\"gender\" value=\"여\"/>여자<br/>\r\n");
      out.write("		나이 : <input type=\"number\" name=\"age\"/>\r\n");
      out.write("		\r\n");
      out.write("		<hr/>\r\n");
      out.write("		\r\n");
      out.write("		<h2>당신이 가장 좋아하는 ____는?</h2>\r\n");
      out.write("		당신이 가장 좋아하는 음료는? <input type=\"text\" name=\"beverage\"/><br/>\r\n");
      out.write("		당신이 가장 좋아하는 물건1은? <input type=\"text\" name=\"product\"/><br/>\r\n");
      out.write("		당신이 가장 좋아하는 물건2는? <input type=\"text\" name=\"product\"/><br/>\r\n");
      out.write("		당신이 가장 좋아하는 물건3은? <input type=\"text\" name=\"product\"/><br/>\r\n");
      out.write("		당신이 가장 좋아하는 책은? <input type=\"text\" name=\"book\"/><br/>\r\n");
      out.write("		당신이 가장 좋아하는 영화는? <input type=\"text\" name=\"moive\"/><br/>\r\n");
      out.write("			\r\n");
      out.write("		<br/>\r\n");
      out.write("		\r\n");
      out.write("		<input type=\"submit\" value=\"전송\"/>\r\n");
      out.write("				\r\n");
      out.write("	</form>\r\n");
      out.write("	\r\n");
      out.write("	<hr/>\r\n");
      out.write("	\r\n");
      out.write("	<form action=\"01_2_elEnd.jsp\">\r\n");
      out.write("		<input type=\"text\" name=\"name\" placeholder=\"제품명을 입력하세요\"/><br/>\r\n");
      out.write("		<input type=\"number\" name=\"count\" placeholder=\"수량을 입력하세요\"/><br/>\r\n");
      out.write("		<input type=\"text\" name=\"option\" placeholder=\"옵션1\"/><br/>\r\n");
      out.write("		<input type=\"text\" name=\"option\" placeholder=\"옵션2\"/><br/>\r\n");
      out.write("		<input type=\"submit\" value=\"제출\"/>\r\n");
      out.write("	</form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
